from paralleldots.config import get_api_key
import requests
import json

def get_keywords( text ):
	apikey  = get_api_key()
	if not apikey == None:
		if type( text ) != str:
			return "Input must be a string." 
		elif text == "":
			return "Input string cannot be empty."
		
		url = 'http://apis.paralleldots.com/keywords'
		response = requests.post( url, params={ "apikey": api_key, "q": text } )
		if response.status_code != 200:
			return "Oops something went wrong ! You can raise an issue at https://github.com/ParallelDots/ParallelDots-Python-API/issues."
		response = { "keywords": json.loads( response.content ) }
		response["usage"] = "By accessing ParallelDots API or using information generated by ParallelDots API, you are agreeing to be bound by the ParallelDots API Terms of Use: http://www.paralleldots.com/terms-and-conditions"
		return response
	else:
		return "API key does not exist"