from paralleldots.config import get_api_key
import requests
import json

def get_specific_hit_count( end_point ):
	apikey  = get_api_key()
	if not apikey == None:
		if type( end_point ) != str:
			return "Input must be a string." 
		url = "http://apis.paralleldots.com/specific_hit_count"
		r =  requests.post( url, params={ "apikey": apikey, "end_point": end_point } )
		if r.status_code != 200:
			return "Oops something went wrong ! You can raise an issue at https://github.com/ParallelDots/ParallelDots-Python-API/issues."
		r = json.loads( r.text )
		r["usage"] = "By accessing ParallelDots API or using information generated by ParallelDots API, you are agreeing to be bound by the ParallelDots API Terms of Use: http://www.paralleldots.com/terms-and-conditions"
		return r
	else:
		return "API key does not exist"